
import React from 'react';
import { ArticleParagraph } from '../types';

interface ArticleDisplayProps {
  article: ArticleParagraph[];
}

const ArticleDisplay: React.FC<ArticleDisplayProps> = ({ article }) => {

  const printStyles = `
    <style>
        body { font-family: 'Comic Sans MS', cursive, sans-serif; padding: 20px; color: #333; margin: 0; background: #f0f8ff; }
        .article-container { max-width: 800px; margin: 0 auto; padding: 30px; border: 2px dashed #9AE6B4; border-radius: 15px; background: #FFFEE0; box-shadow: 0 5px 15px rgba(0,0,0,0.1); }
        h1 { color: #F687B3; text-align: center; font-size: 2.8em; margin-bottom: 25px; text-shadow: 2px 2px #FFC0CB; }
        .paragraph-block { margin-bottom: 40px; page-break-inside: avoid; border-bottom: 1px solid #eee; padding-bottom: 20px; }
        .paragraph-block:last-child { border-bottom: none; }
        p { font-size: 1.3em; line-height: 1.6; margin-bottom: 20px; text-align: left; }
        img { max-width: 100%; height: auto; display: block; margin: 25px auto; border: 5px solid #63B3ED; border-radius: 10px; box-shadow: 0 3px 10px rgba(0,0,0,0.2); }
        .footer { text-align: center; margin-top: 40px; font-size: 0.9em; color: #6B7280; }
        @media print {
            body { background: none; padding: 0; }
            .article-container { border: none; box-shadow: none; padding: 0; max-width: 100%; }
        }
    </style>
  `;

  const handlePrintAll = () => {
    const printWindow = window.open('', '', 'height=800,width=1000');
    if (printWindow) {
      const fullContent = article.map((p, i) => `
        <div class="paragraph-block">
          <p>${p.text}</p>
          ${p.imageUrl ? `<img src="${p.imageUrl}" alt="Illustration ${i + 1}" />` : ''}
        </div>
      `).join('');

      printWindow.document.write(`
        <html>
        <head>
            <title>AI Kids News - Full Article</title>
            ${printStyles}
        </head>
        <body>
            <div class="article-container">
                <h1>AI Kids News</h1>
                ${fullContent}
                <div class="footer">Generated by AI Kids News - Making learning fun!</div>
            </div>
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
      printWindow.close();
    } else {
      alert('Please allow pop-ups to print the article.');
    }
  };

  const handleShareArticle = async () => {
    const firstPara = article[0]?.text || '';
    const summary = firstPara.length > 150 ? firstPara.substring(0, 147) + '...' : firstPara;
    const shareTitle = 'AI Kids News - Check this out!';
    const shareText = `Check out this awesome AI Kids news article! 📰✨\n\nSummary: ${summary}`;
    const shareUrl = window.location.origin + window.location.pathname;

    if (navigator.share) {
      try {
        await navigator.share({
          title: shareTitle,
          text: shareText,
          url: shareUrl,
        });
      } catch (error) {
        if ((error as Error).name !== 'AbortError') {
          console.error('Error sharing article:', error);
        }
      }
    } else {
      const fullShareContent = `${shareTitle}\n\n${shareText}\n\nRead more at: ${shareUrl}`;
      navigator.clipboard.writeText(fullShareContent)
        .then(() => alert('Article summary and link copied to clipboard! 📋'))
        .catch(err => console.error('Could not copy text: ', err));
    }
  };

  const handlePrintParagraph = (index: number) => {
    const paragraphElement = document.getElementById(`paragraph-content-${index}`);
    if (paragraphElement) {
      const printWindow = window.open('', '', 'height=600,width=800');
      if (printWindow) {
        printWindow.document.write(`
          <html>
          <head>
              <title>AI Kids News Paragraph</title>
              ${printStyles}
          </head>
          <body>
              <div class="article-container">
                  <h1>AI Kids News</h1>
                  <div class="paragraph-block">
                    ${paragraphElement.innerHTML}
                  </div>
                  <div class="footer">Generated by AI Kids News - Making learning fun!</div>
              </div>
          </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.focus();
        printWindow.print();
        printWindow.close();
      } else {
        alert('Please allow pop-ups to print the article.');
      }
    }
  };

  const handleShareParagraph = async (paragraph: ArticleParagraph) => {
    const shareText = `Check out this funny AI Kids News paragraph! 🎉\n\n${paragraph.text}`;
    if (navigator.share) {
      try {
        const absoluteUrl = window.location.origin + window.location.pathname; 
        await navigator.share({
          title: 'AI Kids News - Fun Fact!',
          text: shareText,
          url: absoluteUrl,
        });
      } catch (error) {
        if ((error as Error).name !== 'AbortError') {
          console.error('Error sharing paragraph:', error);
        }
      }
    } else {
      navigator.clipboard.writeText(shareText)
        .then(() => alert('Paragraph copied to clipboard!'))
        .catch(err => console.error('Could not copy text: ', err));
    }
  };

  return (
    <div className="mt-8">
      <div className="flex flex-col items-center mb-8 no-print">
        <h2 className="text-4xl font-extrabold text-green-700 text-center mb-6">
          Your Awesome Article!
        </h2>
        <div className="flex flex-col sm:flex-row gap-4 w-full justify-center px-4">
          <button
            onClick={handlePrintAll}
            className="flex-1 max-w-xs bg-green-600 text-white font-bold py-4 px-8 rounded-full shadow-lg hover:bg-green-700 transition duration-300 ease-in-out transform hover:scale-105 flex items-center justify-center text-xl"
            aria-label="Print Entire Article"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print Full
          </button>
          <button
            onClick={handleShareArticle}
            className="flex-1 max-w-xs bg-purple-600 text-white font-bold py-4 px-8 rounded-full shadow-lg hover:bg-purple-700 transition duration-300 ease-in-out transform hover:scale-105 flex items-center justify-center text-xl"
            aria-label="Share Entire Article"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
            </svg>
            Share Full
          </button>
        </div>
      </div>

      <div className="grid gap-8">
        {article.map((paragraph, index) => (
          <div
            key={index}
            className="printable-area bg-white rounded-xl shadow-lg p-6 md:p-8 flex flex-col items-center border border-indigo-200"
          >
            <div id={`paragraph-content-${index}`} className="flex flex-col items-center w-full">
              <p className="text-xl md:text-2xl text-gray-800 leading-relaxed mb-6 text-center lg:text-left">
                {paragraph.text}
              </p>
              {paragraph.imageUrl && (
                <img
                  src={paragraph.imageUrl}
                  alt={`Illustration ${index + 1}`}
                  className="w-full max-w-sm md:max-w-md h-auto rounded-lg shadow-md mb-6 object-cover transform transition duration-300 ease-in-out hover:scale-105"
                  onError={(e) => {
                    e.currentTarget.src = 'https://picsum.photos/400/400?random=' + index;
                  }}
                />
              )}
            </div>
            <div className="no-print flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4 mt-4 w-full justify-center">
              <button
                onClick={() => handlePrintParagraph(index)}
                className="bg-blue-500 text-white font-semibold py-2 px-4 rounded-lg flex items-center justify-center hover:bg-blue-600 transition duration-300"
                aria-label={`Print paragraph ${index + 1}`}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M5 4V2a2 2 0 012-2h6a2 2 0 012 2v2h2a2 2 0 012 2v8a2 2 0 01-2 2h-2v2a2 2 0 01-2 2H7a2 2 0 01-2-2v-2H3a2 2 0 01-2-2V6a2 2 0 012-2h2zm2 0h6v2H7V4zm-2 6H3V6h2v4zm8 0h2V6h-2v4zM7 16h6v-4H7v4z" clipRule="evenodd" />
                </svg>
                Print Paragraph
              </button>
              <button
                onClick={() => handleShareParagraph(paragraph)}
                className="bg-purple-500 text-white font-semibold py-2 px-4 rounded-lg flex items-center justify-center hover:bg-purple-600 transition duration-300"
                aria-label={`Share paragraph ${index + 1}`}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M15 8a3 3 0 10-2.977-2.977l-4.212 2.106a2.983 2.983 0 000 5.742l4.212 2.106A3 3 0 1015 12a3 3 0 00-2.977-2.977l-4.212-2.106a2.983 2.983 0 000-5.742l4.212-2.106A3 3 0 1015 8z" />
                </svg>
                Share
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ArticleDisplay;
